apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-sample-app
  description: An example of a python application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: JamesAtIntegratnIO/python-sample-flask-application
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: user:guest
  lifecycle: experimental
  providesApis:
    - python-sample-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: python-sample-api
  description: An example of a python API.
  # Example for optional annotations
  annotations:
    github.com/project-slug: JamesAtIntegratnIO/python-sample-flask-application
    backstage.io/techdocs-ref: dir:.
spec:
  type: openapi
  owner: user:guest
  lifecycle: experimental
  system: python-sample-app
  definition: swagger.yml
  
